"""Web3 provenance for DALANG output — dep-free, deterministic, offline.

Every animatic gets a cryptographic fingerprint + a content identifier + optional
mint-ready NFT metadata, so an agent that paid for a render (via x402 on X Layer)
can prove authorship and mint/pin it on-chain. Pure stdlib — no eth libs, no RPC.

- content_sha256: keccak-free SHA-256 fingerprint (0x-hex), the canonical bytes id.
- content_cid:    CIDv1 (raw codec, sha2-256) — a real IPFS content address
                  (bafkrei…). Matches `ipfs add --raw-leaves` single-block CIDs;
                  for large chunked files, treat it as the exact-bytes fingerprint.
- erc721_metadata: OpenSea/ERC-721 metadata JSON, mint-ready on X Layer.
"""
import base64, hashlib, json

def content_sha256(data: bytes) -> str:
    return "0x" + hashlib.sha256(data).hexdigest()

def content_cid(data: bytes) -> str:
    """CIDv1, raw codec, sha2-256, multibase base32 (starts 'bafkrei')."""
    mh = b"\x12\x20" + hashlib.sha256(data).digest()   # multihash: sha2-256, 32 bytes
    cid = b"\x01\x55" + mh                              # CIDv1, raw codec
    return "b" + base64.b32encode(cid).decode("ascii").lower().rstrip("=")

def erc721_metadata(title: str, description: str, image: str, animation_url: str,
                    attributes: dict, sha256: str, cid: str) -> dict:
    """ERC-721 / OpenSea metadata. `image` (poster) and `animation_url` (the mp4) may
    be data: URIs (self-contained) or ipfs:// URLs once the caller pins the bytes.
    The fingerprint + cid go in `properties` so provenance survives re-hosting."""
    return {
        "name": title or "DALANG animatic",
        "description": (description or "").strip() or "An animatic generated by DALANG.",
        "image": image,
        "animation_url": animation_url,
        "attributes": [{"trait_type": k, "value": v} for k, v in attributes.items() if v not in ("", None)],
        "properties": {
            "generator": "DALANG",
            "created_via": "OKX A2MCP",
            "content_sha256": sha256,
            "content_cid": cid,
            "settlement": "x402 · X Layer (USDT/USDG)",
        },
    }

def demo() -> None:
    # known reference: CIDv1 raw/sha256 of "hello world\n"
    assert content_cid(b"hello world\n").startswith("bafkreifjjcie6ly"), content_cid(b"hello world\n")
    assert content_sha256(b"").startswith("0x") and len(content_sha256(b"")) == 66
    assert content_cid(b"DALANG").startswith("bafkrei")
    m = erc721_metadata("T", " ", "data:image/png;base64,AA", "data:video/mp4;base64,BB",
                        {"Style": "noir", "Shots": 4, "Language": ""}, content_sha256(b"x"), content_cid(b"x"))
    assert m["name"] == "T" and m["description"].startswith("An animatic")
    assert {"trait_type": "Style", "value": "noir"} in m["attributes"]
    assert not any(a["trait_type"] == "Language" for a in m["attributes"])  # empty dropped
    assert m["properties"]["content_cid"].startswith("bafkrei")
    print("provenance self-check ok")

if __name__ == "__main__":
    demo()
