"""Web3 provenance for DALANG output — dep-free, deterministic, offline.

Every animatic gets a cryptographic fingerprint + a content identifier + optional
mint-ready NFT metadata, so an agent that paid for a render (via x402 on X Layer)
can prove authorship and mint/pin it on-chain. Pure stdlib — no eth libs, no RPC.

- content_sha256: keccak-free SHA-256 fingerprint (0x-hex), the canonical bytes id.
- content_cid:    CIDv1 (raw codec, sha2-256) — a real IPFS content address
                  (bafkrei…). Matches `ipfs add --raw-leaves` single-block CIDs;
                  for large chunked files, treat it as the exact-bytes fingerprint.
- erc721_metadata: OpenSea/ERC-721 metadata JSON, mint-ready on X Layer.
"""
import base64, hashlib, json

def content_sha256(data: bytes) -> str:
    return "0x" + hashlib.sha256(data).hexdigest()

def content_cid(data: bytes) -> str:
    """CIDv1, raw codec, sha2-256, multibase base32 (starts 'bafkrei')."""
    mh = b"\x12\x20" + hashlib.sha256(data).digest()   # multihash: sha2-256, 32 bytes
    cid = b"\x01\x55" + mh                              # CIDv1, raw codec
    return "b" + base64.b32encode(cid).decode("ascii").lower().rstrip("=")

def erc721_metadata(title: str, description: str, image: str, animation_url: str,
                    attributes: dict, sha256: str, cid: str,
                    royalty_bps: int = 0, royalty_recipient: str = "") -> dict:
    """ERC-721 / OpenSea metadata. `image` (poster) and `animation_url` (the mp4) may
    be data: URIs (self-contained) or ipfs:// URLs once the caller pins the bytes.
    The fingerprint + cid go in `properties` so provenance survives re-hosting.
    royalty_bps/recipient add EIP-2981-style secondary-sale royalties (X Layer)."""
    m = {
        "name": title or "DALANG animatic",
        "description": (description or "").strip() or "An animatic generated by DALANG.",
        "image": image,
        "animation_url": animation_url,
        "attributes": [{"trait_type": k, "value": v} for k, v in attributes.items() if v not in ("", None)],
        "properties": {
            "generator": "DALANG",
            "created_via": "OKX A2MCP",
            "content_sha256": sha256,
            "content_cid": cid,
            "settlement": "x402 · X Layer (USDT/USDG)",
        },
    }
    if royalty_bps and royalty_recipient:  # OpenSea off-chain royalty hints (NOT on-chain
        m["seller_fee_basis_points"] = int(royalty_bps)  # EIP-2981 — that needs royaltyInfo()
        m["fee_recipient"] = royalty_recipient           # on an ERC-721 the caller deploys).
        m["properties"]["royalty"] = {"bps": int(royalty_bps), "recipient": royalty_recipient,
                                      "standard": "opensea-metadata (off-chain)"}
    return m

def provenance_manifest(title: str, sha256: str, cid: str, created_at: int,
                        engine: str) -> dict:
    """A tamper-evident content credential (C2PA-inspired): proves *this* animatic was
    generated by DALANG at a given time. Hash it (manifest_digest) and store the digest
    on X Layer for an on-chain proof-of-creation — authenticity in an age of AI slop."""
    return {
        "spec": "dalang-provenance/1",
        "assertion": "AI-generated animatic produced by DALANG via OKX A2MCP",
        "title": title or "DALANG animatic",
        "generator": "DALANG",
        "engine": engine,
        "created_at": int(created_at),          # unix seconds (server clock)
        "content_sha256": sha256,
        "content_cid": cid,
        "anchor": {"chain": "X Layer",
                   "how": "store manifest_digest on-chain for a tamper-evident record"},
    }

def manifest_digest(manifest: dict) -> str:
    """0x SHA-256 over the canonical manifest JSON — the value to anchor on X Layer."""
    canonical = json.dumps(manifest, sort_keys=True, separators=(",", ":")).encode()
    return "0x" + hashlib.sha256(canonical).hexdigest()

def demo() -> None:
    # known reference: CIDv1 raw/sha256 of "hello world\n"
    assert content_cid(b"hello world\n").startswith("bafkreifjjcie6ly"), content_cid(b"hello world\n")
    assert content_sha256(b"").startswith("0x") and len(content_sha256(b"")) == 66
    assert content_cid(b"DALANG").startswith("bafkrei")
    m = erc721_metadata("T", " ", "data:image/png;base64,AA", "data:video/mp4;base64,BB",
                        {"Style": "noir", "Shots": 4, "Language": ""}, content_sha256(b"x"), content_cid(b"x"))
    assert m["name"] == "T" and m["description"].startswith("An animatic")
    assert {"trait_type": "Style", "value": "noir"} in m["attributes"]
    assert not any(a["trait_type"] == "Language" for a in m["attributes"])  # empty dropped
    assert m["properties"]["content_cid"].startswith("bafkrei")
    assert "seller_fee_basis_points" not in m  # no royalty unless configured
    r = erc721_metadata("T", "d", "i", "a", {"S": "x"}, "0xAA", "bafkreiX", 500, "0xRoyal")
    assert r["seller_fee_basis_points"] == 500 and r["fee_recipient"] == "0xRoyal"
    assert r["properties"]["royalty"]["standard"].startswith("opensea")
    man = provenance_manifest("T", content_sha256(b"x"), content_cid(b"x"), 1_700_000_000, "Ken Burns")
    d1, d2 = manifest_digest(man), manifest_digest(dict(reversed(list(man.items()))))
    assert d1.startswith("0x") and d1 == d2  # digest is canonical (key order independent)
    print("provenance self-check ok")

if __name__ == "__main__":
    demo()
