"""Web3 provenance for DALANG output — dep-free, deterministic, offline.

Every animatic gets a cryptographic fingerprint + a content identifier + optional
mint-ready NFT metadata, so an agent that paid for a render (via x402 on X Layer)
can prove authorship and mint/pin it on-chain. Pure stdlib — no eth libs, no RPC.

- content_sha256: keccak-free SHA-256 fingerprint (0x-hex), the canonical bytes id.
- content_cid:    CIDv1 (raw codec, sha2-256, bafkrei…) exact-bytes fingerprint.
                  Equals `ipfs add --raw-leaves` only for single-block files (<=256 KiB);
                  a chunked mp4 gets a different UnixFS DAG root, so this is a fingerprint
                  anyone can recompute — NOT a resolvable pin address for large files.
- erc721_metadata: OpenSea/ERC-721 metadata JSON (off-chain royalty hints / splits),
                  mint-ready on an ERC-721 the caller deploys on X Layer.
"""
import base64, hashlib, json

def content_sha256(data: bytes) -> str:
    return "0x" + hashlib.sha256(data).hexdigest()

def content_cid(data: bytes) -> str:
    """CIDv1, raw codec, sha2-256, multibase base32 (starts 'bafkrei')."""
    mh = b"\x12\x20" + hashlib.sha256(data).digest()   # multihash: sha2-256, 32 bytes
    cid = b"\x01\x55" + mh                              # CIDv1, raw codec
    return "b" + base64.b32encode(cid).decode("ascii").lower().rstrip("=")

def _int(v) -> int:
    """Best-effort int from caller input ('5%', '250', 250, None) — 0 on anything odd, so a
    malformed royalty can't crash a completed paid render."""
    try:
        return int(float(str(v).strip().rstrip("%")))
    except (TypeError, ValueError):
        return 0

def _norm_splits(royalties, royalty_bps: int, royalty_recipient: str) -> list[dict]:
    """Normalize royalty inputs into a clean [{recipient, bps}] split list. `royalties`
    (a co-creator split — every agent that helped make the video) wins; else fall back to
    the single legacy royalty_bps/recipient. Tolerates caller junk (non-dict entries, '5%'
    strings, missing keys) — a bad royalty must never discard an expensive render."""
    splits = list(royalties) if isinstance(royalties, list) else (
        [{"recipient": royalty_recipient, "bps": royalty_bps}] if royalty_recipient and royalty_bps else [])
    out = []
    for s in splits:
        if not isinstance(s, dict):
            continue
        r, bps = str(s.get("recipient") or "").strip(), _int(s.get("bps"))
        if r and bps > 0:
            out.append({"recipient": r, "bps": bps})
    return out

def erc721_metadata(title: str, description: str, image: str, animation_url: str,
                    attributes: dict, sha256: str, cid: str,
                    royalty_bps: int = 0, royalty_recipient: str = "",
                    royalties: list | None = None) -> dict:
    """ERC-721 / OpenSea metadata. `image` (poster) and `animation_url` (the mp4) may
    be data: URIs (self-contained) or ipfs:// URLs once the caller pins the bytes.
    The fingerprint + cid go in `properties` so provenance survives re-hosting.
    royalties: a co-creator split [{recipient, bps}, ...] — each agent in the supply
    chain co-owns the asset. These are OpenSea off-chain hints (NOT on-chain EIP-2981,
    which needs royaltyInfo() on the ERC-721 the caller deploys); the split is the intent."""
    m = {
        "name": title or "DALANG animatic",
        "description": (description or "").strip() or "An animatic generated by DALANG.",
        "image": image,
        "animation_url": animation_url,
        "attributes": [{"trait_type": k, "value": v} for k, v in attributes.items() if v not in ("", None)],
        "properties": {
            "generator": "DALANG",
            "created_via": "OKX A2MCP",
            "content_sha256": sha256,
            "content_cid": cid,
            "settlement": "x402 · X Layer (USDT/USDG)",
        },
    }
    splits = _norm_splits(royalties, royalty_bps, royalty_recipient)
    if splits:
        total = sum(s["bps"] for s in splits)
        m["seller_fee_basis_points"] = total          # OpenSea single field: the total royalty
        m["fee_recipient"] = splits[0]["recipient"]   # OpenSea single payee: first co-creator
        m["properties"]["royalty"] = {"total_bps": total, "splits": splits,
                                      "standard": "opensea-metadata (off-chain)"}
    return m

def provenance_manifest(title: str, sha256: str, cid: str, created_at: int,
                        engine: str, parent_cid: str = "") -> dict:
    """A tamper-evident content credential (C2PA-inspired): proves *this* animatic was
    generated by DALANG at a given time. Hash it (manifest_digest) and store the digest
    on X Layer for an on-chain proof-of-creation — authenticity in an age of AI slop.
    parent_cid: the content_cid this render remixes — links renders into a verifiable
    on-chain remix DAG (the digest covers it, so lineage is tamper-evident too)."""
    m = {
        "spec": "dalang-provenance/1",
        "assertion": "AI-generated animatic produced by DALANG via OKX A2MCP",
        "title": title or "DALANG animatic",
        "generator": "DALANG",
        "engine": engine,
        "created_at": int(created_at),          # unix seconds (server clock)
        "content_sha256": sha256,
        "content_cid": cid,
        "anchor": {"chain": "X Layer",
                   "how": "store manifest_digest on-chain for a tamper-evident record"},
    }
    if parent_cid:  # remix lineage: this animatic descends from parent_cid
        m["parent_cid"] = parent_cid
    return m

def manifest_digest(manifest: dict) -> str:
    """0x SHA-256 over the canonical manifest JSON — the value to anchor on X Layer."""
    canonical = json.dumps(manifest, sort_keys=True, separators=(",", ":")).encode()
    return "0x" + hashlib.sha256(canonical).hexdigest()

def demo() -> None:
    # known reference: CIDv1 raw/sha256 of "hello world\n"
    assert content_cid(b"hello world\n").startswith("bafkreifjjcie6ly"), content_cid(b"hello world\n")
    assert content_sha256(b"").startswith("0x") and len(content_sha256(b"")) == 66
    assert content_cid(b"DALANG").startswith("bafkrei")
    m = erc721_metadata("T", " ", "data:image/png;base64,AA", "data:video/mp4;base64,BB",
                        {"Style": "noir", "Shots": 4, "Language": ""}, content_sha256(b"x"), content_cid(b"x"))
    assert m["name"] == "T" and m["description"].startswith("An animatic")
    assert {"trait_type": "Style", "value": "noir"} in m["attributes"]
    assert not any(a["trait_type"] == "Language" for a in m["attributes"])  # empty dropped
    assert m["properties"]["content_cid"].startswith("bafkrei")
    assert "seller_fee_basis_points" not in m  # no royalty unless configured
    r = erc721_metadata("T", "d", "i", "a", {"S": "x"}, "0xAA", "bafkreiX", 500, "0xRoyal")
    assert r["seller_fee_basis_points"] == 500 and r["fee_recipient"] == "0xRoyal"
    assert r["properties"]["royalty"]["standard"].startswith("opensea")
    # co-creator splits: every agent that helped make the video co-owns it
    sp = erc721_metadata("T", "d", "i", "a", {"S": "x"}, "0xAA", "bafkreiX", royalties=[
        {"recipient": "0xTrend", "bps": 200}, {"recipient": "0xWriter", "bps": 300},
        {"recipient": "0xDalang", "bps": 500}, {"recipient": "0xEmpty", "bps": 0}])  # zero dropped
    assert sp["seller_fee_basis_points"] == 1000 and sp["fee_recipient"] == "0xTrend"
    assert len(sp["properties"]["royalty"]["splits"]) == 3  # the zero-bps entry is dropped
    man = provenance_manifest("T", content_sha256(b"x"), content_cid(b"x"), 1_700_000_000, "Ken Burns")
    assert "parent_cid" not in man  # no lineage unless it's a remix
    d1, d2 = manifest_digest(man), manifest_digest(dict(reversed(list(man.items()))))
    assert d1.startswith("0x") and d1 == d2  # digest is canonical (key order independent)
    child = provenance_manifest("T2", content_sha256(b"y"), content_cid(b"y"), 1_700_000_001,
                                "Ken Burns", parent_cid=content_cid(b"x"))
    assert child["parent_cid"] == content_cid(b"x")  # remix points at its parent
    assert manifest_digest(child) != d1  # lineage is covered by the tamper-evident digest
    print("provenance self-check ok")

if __name__ == "__main__":
    demo()
